name: Java CI

on:
    push:
        branches: [ master ]

jobs:

    build-and-analyze:

        name: Build and Run Sonar analysis on JDK 17
        runs-on: ubuntu-20.04
        steps:

            -   name: Checkout Code
                uses: actions/checkout@v3
                with:
                    # Disabling shallow clone for improving relevancy of SonarQube reporting
                    fetch-depth: 0

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: 'maven'

            # Cache Sonar packages which as used to run analysis and collect metrics
            -   name: Cache SonarCloud packages
                uses: actions/cache@v3
                with:
                    path: ~/.sonar/cache
                    key: ${{ runner.os }}-sonar
                    restore-keys: ${{ runner.os }}-sonar

            # Some tests need screen access
            -   name: Install xvfb
                run: sudo apt-get install -y xvfb

            -   name: Build with Maven and run SonarQube analysis
                run: xvfb-run ./mvnw -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=tu-yucheng_sonarqube-maven -Dsonar.organization=tuyucheng -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
                env:
                    # These two env variables are needed for sonar analysis
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}